Repository plot-timer/plot-server, pull requests merged in 2023-08, with the labels that each got.

#18 2 email login
  plot-server/.gitignore
  plot-server/build.gradle
  plot-server/src/main/java/com/plot/plotserver/TestDataInit.java
  plot-server/src/main/java/com/plot/plotserver/config/SchedulingConfig.java
  plot-server/src/main/java/com/plot/plotserver/config/mailConfig.java
  plot-server/src/main/java/com/plot/plotserver/controller/EmailController.java
  plot-server/src/main/java/com/plot/plotserver/domain/EmailTmp.java
  plot-server/src/main/java/com/plot/plotserver/domain/History.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/email/EmailCodeReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/email/EmailRequestDto.java
  plot-server/src/main/java/com/plot/plotserver/exception/CustomExceptionHandler.java
  plot-server/src/main/java/com/plot/plotserver/exception/email/EmailCodeExpiredException.java
  plot-server/src/main/java/com/plot/plotserver/exception/email/EmailCodeMismatchException.java
  plot-server/src/main/java/com/plot/plotserver/exception/email/EmailCodeSendingFailureException.java
  plot-server/src/main/java/com/plot/plotserver/repository/EmailTmpRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/UserRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/EmailService.java
  plot-server/src/main/java/com/plot/plotserver/service/SchedulerService.java
  plot-server/src/main/resources/templates/mail.html
  plot-server/src/main/resources/templates/mail2.html
  plot-server/src/main/resources/templates/plot_logo.png
Labels: New Feature, fix, build

#26 Feat: TagRepository, TagCategoryRepository 생성, Tag, TagCategory entit…
  plot-server/src/main/java/com/plot/plotserver/domain/Category.java
  plot-server/src/main/java/com/plot/plotserver/domain/TagCategory.java
  plot-server/src/main/java/com/plot/plotserver/domain/Todo.java
  plot-server/src/main/java/com/plot/plotserver/domain/User.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/NewCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/UpdateCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagCategoryRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
Labels: New Feature, fix

#30 29 feat tag
  plot-server/src/main/java/com/plot/plotserver/controller/CategoryController.java
  plot-server/src/main/java/com/plot/plotserver/controller/TagController.java
  plot-server/src/main/java/com/plot/plotserver/domain/Category.java
  plot-server/src/main/java/com/plot/plotserver/domain/Tag.java
  plot-server/src/main/java/com/plot/plotserver/domain/TagCategory.java
  plot-server/src/main/java/com/plot/plotserver/domain/User.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/NewCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/UpdateCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/tag/SearchTagReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category/CategoryResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/tag/TagResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/exception/CustomExceptionHandler.java
  plot-server/src/main/java/com/plot/plotserver/exception/category/CategoryNotExistException.java
  plot-server/src/main/java/com/plot/plotserver/repository/CategoryRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagCategoryRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TodoRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/TagService.java
Labels: New Feature, fix, refactor

#32 Feat: 구글 소셜 로그인 기능 구현 #31
  plot-server/src/main/java/com/plot/plotserver/oauth2/GoogleUserInfo.java
  plot-server/src/main/java/com/plot/plotserver/oauth2/KakaoUserInfo.java
  plot-server/src/main/java/com/plot/plotserver/oauth2/NaverUserInfo.java
  plot-server/src/main/java/com/plot/plotserver/oauth2/OAuth2UserInfo.java
  plot-server/src/main/java/com/plot/plotserver/oauth2/OauthTokenProvider.java
  plot-server/src/main/java/com/plot/plotserver/oauth2/OauthUserInfoProvider.java
  plot-server/src/main/java/com/plot/plotserver/service/SocialLoginService.java
Labels: New Feature

#37 22 todo management
  plot-server/src/main/java/com/plot/plotserver/controller/DailyTodoController.java
  plot-server/src/main/java/com/plot/plotserver/controller/HistoryController.java
  plot-server/src/main/java/com/plot/plotserver/domain/CategoryGroup.java
  plot-server/src/main/java/com/plot/plotserver/domain/DailyTodo.java
  plot-server/src/main/java/com/plot/plotserver/domain/Record.java
  plot-server/src/main/java/com/plot/plotserver/domain/Todo.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/DailyTodo/NewDailyTodoReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/DailyTodo/UpdateDailyTodoReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/history/HistoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/todo/UpdateTodoDto.java
  plot-server/src/main/java/com/plot/plotserver/exception/CustomExceptionHandler.java
  plot-server/src/main/java/com/plot/plotserver/exception/dailytodo/DailyTodoAlreadyExistException.java
  plot-server/src/main/java/com/plot/plotserver/exception/dailytodo/DailyTodoDeleteFailException.java
  plot-server/src/main/java/com/plot/plotserver/exception/dailytodo/DailyTodoSavedFailException.java
  plot-server/src/main/java/com/plot/plotserver/exception/dailytodo/DailyTodoUpdateFailException.java
  plot-server/src/main/java/com/plot/plotserver/exception/history/HistorySavedFailException.java
  plot-server/src/main/java/com/plot/plotserver/repository/DailyTodoRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/EmailTmpRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/RecordRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/RefreshTokenRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryGroupService.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/DailyTodoService.java
  plot-server/src/main/java/com/plot/plotserver/service/HistoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/TodoService.java
  plot-server/src/main/java/com/plot/plotserver/util/DailyTodoStatusEnum.java
  plot-server/src/test/resources/application.yaml
Labels: New Feature, refactor

#40 39 feat daily todo
  plot-server/src/main/java/com/plot/plotserver/controller/DailyTodoController.java
  plot-server/src/main/java/com/plot/plotserver/controller/ScheduleController.java
  plot-server/src/main/java/com/plot/plotserver/controller/TagCategoryController.java
  plot-server/src/main/java/com/plot/plotserver/domain/DailyTodo.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/DailyTodo/SearchDailyTodo.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/dailyTodo/DailyTodoResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/repository/DailyTodoRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/RecordRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/RefreshTokenRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/DailyTodoService.java
  plot-server/src/main/java/com/plot/plotserver/service/ScheduleService.java
  plot-server/src/main/java/com/plot/plotserver/service/SchedulerService.java
Labels: New Feature

#42 Fix: History 시작, 끝 날짜 다를때, 날짜별로 DailyTodo, History 자동 생성 #41
  plot-server/src/main/java/com/plot/plotserver/service/HistoryService.java
Labels: fix

#47 46 feat todo 재생
  plot-server/src/main/java/com/plot/plotserver/controller/CategoryController.java
  plot-server/src/main/java/com/plot/plotserver/controller/TodoController.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category/CategoryTodosResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/todo/TodoResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/exception/CustomExceptionHandler.java
  plot-server/src/main/java/com/plot/plotserver/exception/todo/TodoSearchFailException.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/TodoService.java
Labels: New Feature

#50 22 todo management
  plot-server/src/main/java/com/plot/plotserver/controller/CategoryGroupController.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category/CategoryResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category_group/CategoryGroupResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryGroupService.java
Labels: New Feature

#52 Refactor: CategoryService, TodoService save, update 성능 최적화 및 의존관계 줄이기…
  plot-server/src/main/java/com/plot/plotserver/controller/CategoryController.java
  plot-server/src/main/java/com/plot/plotserver/controller/TodoController.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/NewCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/UpdateCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/todo/NewTodoReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/todo/UpdateTodoDto.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/TodoService.java
Labels: refactor

#53 Fix: Todo save할때, TodoResponseDto 반환 #22
  plot-server/src/main/java/com/plot/plotserver/controller/TodoController.java
  plot-server/src/main/java/com/plot/plotserver/service/TodoService.java
Labels: fix

#54 36 test repository
  plot-server/.gitignore
  plot-server/build.gradle
  plot-server/src/main/java/com/plot/plotserver/controller/CategoryGroupController.java
  plot-server/src/main/java/com/plot/plotserver/controller/DailyTodoController.java
  plot-server/src/main/java/com/plot/plotserver/controller/EmailController.java
  plot-server/src/main/java/com/plot/plotserver/domain/Category.java
  plot-server/src/main/java/com/plot/plotserver/domain/CategoryGroup.java
  plot-server/src/main/java/com/plot/plotserver/domain/DailyTodo.java
  plot-server/src/main/java/com/plot/plotserver/domain/Record.java
  plot-server/src/main/java/com/plot/plotserver/domain/TagCategory.java
  plot-server/src/main/java/com/plot/plotserver/domain/Todo.java
  plot-server/src/main/java/com/plot/plotserver/domain/User.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/NewCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/category/UpdateCategoryReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/categorygroup/NewCategoryGroupReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/request/categorygroup/UpdateCategoryGroupReqDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category/CategoryResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/dto/response/category_group/CategoryGroupResponseDto.java
  plot-server/src/main/java/com/plot/plotserver/repository/CategoryGroupRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/CategoryRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/DailyTodoRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagCategoryRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TagRepository.java
  plot-server/src/main/java/com/plot/plotserver/repository/TodoRepository.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryGroupService.java
  plot-server/src/main/java/com/plot/plotserver/service/CategoryService.java
  plot-server/src/main/java/com/plot/plotserver/service/DailyTodoService.java
  plot-server/src/main/java/com/plot/plotserver/service/EmailSendingService.java
  plot-server/src/main/java/com/plot/plotserver/service/TodoService.java
  plot-server/src/test/java/com/plot/plotserver/repository/CategoryGroupRepositoryTest.java
  plot-server/src/test/java/com/plot/plotserver/repository/CategoryRepositoryTest.java
Labels: refactor
